openapi: 3.0.0
info:
  title: Notifications SQS Message Types
  version: '1.0.0'
  description: |-
    Notifications SQS Message Types
    
    Whilst this is an openAPI spec, it does not define being used to define REST APIs, nor is it intended to.
    
    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**
    
    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required 
    elements.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/send-uk-gov-notify-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendNotifyMessage'
      responses:
        '204':
          description: No response content.

components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:
    SendNotifyMessage:
      title: SendNotifyMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages
      properties:
        channel:
          $ref: '#/components/schemas/Channel'
        sourceType:
          $ref: '#/components/schemas/SourceType'
        sourceReference:
          type: string
          description: Reference in the source of the application this message relates
        gssCode:
          type: string
          description: GSS code of the ERO responsible for sending the message
        requestor:
          type: string
          description: Identifier of the user or system responsible for sending the message
        toAddress:
          $ref: '#/components/schemas/MessageAddress'
        messageType:
          $ref: '#/components/schemas/MessageType'
        personalisation:
          $ref: '#/components/schemas/TemplatePersonalisation'
      required:
        - channel
        - sourceType
        - sourceReference
        - gssCode
        - requestor
        - toAddress
        - messageType

    TemplatePersonalisation:
      title: TemplatePersonalisation
      type: array
      description: Template personalisation values to replace each template placeholder.
      items:
        type: object
        properties:
          name:
            type: string
            example: "applicant-name"
          value:
            type: string
            example: "John"
      required:
        - name
        - value

    Channel:
      title: Channel
      type: string
      enum:
        - email

    SourceType:
      title: SourceType
      type: string
      enum:
        - voter-card

    MessageType:
      title: MessageType
      type: string
      enum:
        - application-received
        - application-approved
        - application-rejected
        - photo-resubmission

    MessageAddress:
      type: object
      description: Address type needs to match message type
      properties:
        emailAddress:
          type: string
          format: email
        postalAddress:
          type: object
          properties:
            address_line_1:
              type: string
            address_line_2:
              type: string
            address_line_3:
              type: string
            address_line_4:
              type: string
            address_line_5:
              type: string
            address_line_6:
              type: string
            address_line_7:
              type: string
        smsNumber:
          type: string

  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses: { }

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    SendNotifyMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendNotifyMessage'
