openapi: 3.0.0
info:
  title: Notifications SQS Message Types
  version: '1.0.0'
  description: |-
    Notifications SQS Message Types
    
    Whilst this is an openAPI spec, it does not define being used to define REST APIs, nor is it intended to.
    
    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**
    
    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required 
    elements.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/send-notify-email':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/NotifySend'
      responses:
        '204':
          description: No response content.

components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:
    NotifySendMessage:
      title: NotifySendMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages
      properties:
        applicationId:
          type: string
        referenceId:
          type: string
          description: Client reference for message
        toAddress:
          $ref: '#/components/schemas/MessageAddress'
        messageType:
          $ref: '#/components/schemas/MessageType'
        personalisation:
          $ref: '#/components/schemas/TemplatePersonalisation'
      required:
        - applicationId
        - referenceId
        - messageType
        - personalisation

    TemplatePersonalisation:
      title: TemplatePersonalisation
      type: array
      description: Template personalisation values to replace in the template.
      items:
        type: object
        properties:
          name:
            type: string
          value:
            type: string

    MessageType:
      title: MessageType
      type: string
      enum:
        - applicationreceived
        - applicationrejected
        - applicationapproved

    MessageAddress:
      type: object
      description: Address type needs to match message type
      properties:
        emailAddress:
          type: string
          format: email
        address:
          type: object
          properties:
            address_line_1:
              type: string
            address_line_2:
              type: string
            address_line_3:
              type: string
            address_line_4:
              type: string
            address_line_5:
              type: string
            address_line_6:
              type: string
            address_line_7:
              type: string
        phoneNumber:
          type: string

  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses: { }

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    NotifySend:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotifySendMessage'
