openapi: 3.0.0
info:
  title: Notifications SQS Message Types
  version: '1.7.0'
  description: |-
    Notifications SQS Message Types
    
    Whilst this is an openAPI spec, it does not define being used to define REST APIs, nor is it intended to.
    
    The `paths` elements are being used to document (at a high level) the SQS queues and the request bodies that are expected
    to be published to them. **There is no intent to generate or implement SQS queues or listener classes from this document.**
    
    The `paths` element is only being used in order to maintain the structure of the openApi spec, as `paths` are required 
    elements.
#
# --------------------------------------------------------------------------------
#

paths:
  #
  # --------------------------------------------------------------------------------
  # SQS Queues start here
  # --------------------------------------------------------------------------------
  #
  '/send-uk-gov-notify-photo-resubmission-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendNotifyPhotoResubmissionMessage'
      responses:
        '204':
          description: No response content.

  '/send-uk-gov-notify-id-document-resubmission-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendNotifyIdDocumentResubmissionMessage'
      responses:
        '204':
          description: No response content.

  '/send-uk-gov-notify-application-approved-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendNotifyApplicationApprovedMessage'
      responses:
        '204':
          description: No response content.

  '/send-uk-gov-notify-application-rejected-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/SendNotifyApplicationRejectedMessage'
      responses:
        '204':
          description: No response content.

  '/remove-application-notifications-message':
    post:
      tags:
        - SQS Queues
      requestBody:
        $ref: '#/components/requestBodies/RemoveApplicationNotificationsMessage'
      responses:
        '204':
          description: No response content.

components:
  #
  # Schema and Enum Definitions
  # --------------------------------------------------------------------------------
  schemas:
    SendNotifyMessage:
      title: SendNotifyMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages. This is a generic message format which can be extended for various template types.
      properties:
        language:
          $ref: '#/components/schemas/Language'
        sourceType:
          $ref: '#/components/schemas/SourceType'
        sourceReference:
          type: string
          description: Reference in the source of the application this message relates
        gssCode:
          type: string
          description: GSS code of the ERO responsible for sending the message
        requestor:
          type: string
          description: Identifier of the user or system responsible for sending the message
        toAddress:
          $ref: '#/components/schemas/MessageAddress'
        messageType:
          $ref: '#/components/schemas/MessageType'
      required:
        - language
        - sourceType
        - sourceReference
        - gssCode
        - requestor
        - toAddress
        - messageType

    SendNotifyPhotoResubmissionMessage:
      title: SendNotifyPhotoResubmissionMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages for Photo resubmission
      allOf:
        - $ref: '#/components/schemas/SendNotifyMessage'
      properties:
        channel:
          $ref: '#/components/schemas/NotificationChannel'
        personalisation:
          $ref: '#/components/schemas/PhotoPersonalisation'
      required:
        - channel
        - personalisation

    SendNotifyIdDocumentResubmissionMessage:
      title: SendNotifyIdDocumentResubmissionMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages for an identification document resubmission
      allOf:
        - $ref: '#/components/schemas/SendNotifyMessage'
      properties:
        channel:
          $ref: '#/components/schemas/NotificationChannel'
        personalisation:
          $ref: '#/components/schemas/IdDocumentPersonalisation'
      required:
        - channel
        - personalisation

    SendNotifyApplicationApprovedMessage:
      title: SendNotifyApplicationApprovedMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages for an approved application
      allOf:
        - $ref: '#/components/schemas/SendNotifyMessage'
      properties:
        personalisation:
          $ref: '#/components/schemas/BasePersonalisation'
      required:
        - personalisation

    SendNotifyApplicationRejectedMessage:
      title: SendNotifyApplicationRejectedMessage
      type: object
      description: SQS Message for sending GOV.UK Notify messages for a rejected application
      allOf:
        - $ref: '#/components/schemas/SendNotifyMessage'
      properties:
        personalisation:
          $ref: '#/components/schemas/ApplicationRejectedPersonalisation'
      required:
        - personalisation

    RemoveApplicationNotificationsMessage:
      title: RemoveApplicationNotificationsMessage
      type: object
      description: SQS Message for removing an application's notifications once the retention period has passed.
      properties:
        sourceType:
          $ref: '#/components/schemas/SourceType'
        sourceReference:
          type: string
          description: Reference of the application in the corresponding source system that the message relates to
      required:
        - sourceType
        - sourceReference

    IdDocumentPersonalisation:
      title: IdDocumentPersonalisation
      type: object
      description: Personalisation details for an identity document resubmission template
      allOf:
        - $ref: '#/components/schemas/BasePersonalisation'
      properties:
        idDocumentRequestFreeText:
          type: string
          description: Free text regarding an identity document request
          example: Please provide a valid identity document
      required:
        - idDocumentRequestFreeText

    PhotoPersonalisation:
      title: PhotoPersonalisation
      type: object
      description: Personalisation details for photo resubmission template
      allOf:
        - $ref: '#/components/schemas/BasePersonalisation'
      properties:
        photoRequestFreeText:
          type: string
          description: Free text regarding photo request
          example: Please provide a clear image
        uploadPhotoLink:
          type: string
          description: The URL link to upload a new image
          example: 'http://localhost:8080/eros/city-council/applications/507f1f77bcf86cd799439011/photos/398c1be2-7950-48a2-aca8-14cb9276a673'
      required:
        - photoRequestFreeText
        - uploadPhotoLink

    ApplicationRejectedPersonalisation:
      title: ApplicationRejectedPersonalisation
      type: object
      description: Personalisation details for application rejected template
      allOf:
        - $ref: '#/components/schemas/BasePersonalisation'
      properties:
        rejectionReasonList:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationRejectionReason'
          example: 'Application is incomplete'
        rejectionReasonMessage:
          type: string
          example: 'Applicant address information is incomplete'
      required:
        - rejectionReasonList

    BasePersonalisation:
      title: BasePersonalisation
      type: object
      description: Basic personalisation details that are common across all templates
      properties:
        applicationReference:
          type: string
          description: The reference number of the Voter Card Application
          example: A3JSZC4CRH
        firstName:
          type: string
          description: The applicant's first name
          example: Fred
        eroContactDetails:
          $ref: '#/components/schemas/ContactDetails'
      required:
        - applicationReference
        - firstName
        - eroContactDetails

    ContactDetails:
      title: ContactDetails
      type: object
      description: Contact details for an ERO
      properties:
        localAuthorityName:
          description: Name of the Local Authority
          type: string
          example: City of Sunderland
        website:
          description: ERO website address
          type: string
          example: "https://ero-address.com"
        phone:
          description: ERO phone number
          type: string
          example: 01234 567890
        email:
          description: Email address for an ERO
          type: string
          example: fred.blogs@some-domain.co.uk
        address:
          $ref: '#/components/schemas/Address'
      required:
        - localAuthorityName
        - website
        - phone
        - email
        - address
    Address:
      title: Address
      description: Address format used throughout gov.uk voter services for an ERO.
      type: object
      x-examples:
        Minimum data:
          street: Street 1
          postcode: PC1 2FB
        Normal Address:
          street: East Lodge
          property: Balruddery
          locality: Invergowrie
          town: Dundee
          area: Angus
          postcode: DD25LF
      properties:
        street:
          type: string
          minLength: 1
          maxLength: 255
          example: Charles Lane
        property:
          type: string
          maxLength: 255
        locality:
          type: string
          maxLength: 255
        town:
          type: string
          maxLength: 255
          example: London
        area:
          type: string
          maxLength: 255
        postcode:
          type: string
          minLength: 1
          maxLength: 10
          example: PE3 6SB
      required:
        - street
        - postcode
    Language:
      title: Language
      description: The language to notify an applicant
      type: string
      enum:
        - cy
        - en
      default: en

    NotificationChannel:
      title: NotificationChannel
      description: The channel to notify an applicant
      type: string
      enum:
        - email
        - letter

    SourceType:
      title: SourceType
      type: string
      enum:
        - voter-card

    MessageType:
      title: MessageType
      type: string
      enum:
        - application-received
        - application-approved
        - application-rejected
        - photo-resubmission
        - id-document-resubmission

    MessageAddress:
      type: object
      description: Address type needs to match message type
      properties:
        emailAddress:
          type: string
          format: email
        postalAddress:
          type: object
          properties:
            addressee:
              type: string
            address:
              $ref: '#/components/schemas/Address'
        smsNumber:
          type: string

    ApplicationRejectionReason:
      title: ApplicationRejectionReason
      description: Enum of reasons why an application was rejected
      type: string
      enum:
        - not-registered-to-vote
        - incomplete-application
        - photo-is-not-acceptable
        - no-response-from-applicant
        - inaccurate-information
        - fraudulent-application
        - other
  #
  # Response Body Definitions
  # --------------------------------------------------------------------------------
  responses: { }

  #
  # Request Body Definitions
  # --------------------------------------------------------------------------------
  requestBodies:
    SendNotifyPhotoResubmissionMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendNotifyPhotoResubmissionMessage'
    SendNotifyIdDocumentResubmissionMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendNotifyIdDocumentResubmissionMessage'
    SendNotifyApplicationApprovedMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendNotifyApplicationApprovedMessage'
    SendNotifyApplicationRejectedMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SendNotifyApplicationRejectedMessage'
    RemoveApplicationNotificationsMessage:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RemoveApplicationNotificationsMessage'
