dynamodb:
  notificationsTableName: ${DYNAMODB_NOTIFICATIONS_TABLE_NAME:notification}

api:
  notify:
    api-key: ${API_NOTIFY_API_KEY}
    template:
        received-email: tbc-received-email-template-id
        approved-email: tbc-approved-email-template-id
        rejected-email: tbc-rejected-email-template-id
        photo-resubmission-email: f1571006-c3a0-4c97-884a-189f5b103f85

sqs:
  send-uk-gov-notify-message-queue-name: ${SQS_SEND_UK_GOV_NOTIFY_MESSAGE_QUEUE_NAME}
