dynamodb:
  notificationsTableName: ${DYNAMODB_NOTIFICATIONS_TABLE_NAME}

api:
  notify:
    api-key: ${API_NOTIFY_API_KEY}
    template:
        received-email-english: tbc-received-email-template-id-en
        received-email-welsh: tbc-received-email-template-id-cy
        approved-email-english: tbc-approved-email-template-id-en
        approved-email-welsh: tbc-approved-email-template-id-cy
        rejected-email-english: tbc-rejected-email-template-id-en
        rejected-email-welsh: tbc-rejected-email-template-id-cy
        photo-resubmission-email-english: ${TEMPLATE_PHOTO_RESUBMISSION_EMAIL_ENGLISH}
        photo-resubmission-email-welsh: ${TEMPLATE_PHOTO_RESUBMISSION_EMAIL_WELSH}
        id-document-resubmission-email-english: ${TEMPLATE_ID_DOCUMENT_RESUBMISSION_EMAIL_ENGLISH}
        id-document-resubmission-email-welsh: ${TEMPLATE_ID_DOCUMENT_RESUBMISSION_EMAIL_WELSH}

sqs:
  send-uk-gov-notify-photo-resubmission-queue-name: ${SQS_SEND_UK_GOV_NOTIFY_PHOTO_RESUBMISSION_QUEUE_NAME}
  send-uk-gov-notify-id-document-resubmission-queue-name: ${SQS_SEND_UK_GOV_NOTIFY_ID_DOCUMENT_RESUBMISSION_QUEUE_NAME}
