dynamodb:
  notificationsTableName: ${DYNAMODB_NOTIFICATIONS_TABLE_NAME}

api:
  notify:
    api-key: ${API_NOTIFY_API_KEY}
    template:
        received-email-english: tbc-received-email-template-id-en
        received-email-welsh: tbc-received-email-template-id-cy
        approved-email-english: tbc-approved-email-template-id-en
        approved-email-welsh: tbc-approved-email-template-id-cy
        rejected-email-english: tbc-rejected-email-template-id-en
        rejected-email-welsh: tbc-rejected-email-template-id-cy
        photo-resubmission-email-english: f1571006-c3a0-4c97-884a-189f5b103f85
        photo-resubmission-email-welsh: e81185e8-000d-49a4-9e96-42311447a62d
        id-document-resubmission-email-english: 296a8fe6-8767-477b-9173-ea9feb82fbda
        id-document-resubmission-email-welsh: 8dfa9c65-0ccf-446f-9a39-3e14f15551d6

sqs:
  send-uk-gov-notify-photo-resubmission-message-queue-name: ${SQS_SEND_UK_GOV_NOTIFY_PHOTO_RESUBMISSION_MESSAGE_QUEUE_NAME}
