dynamodb:
  notificationsTableName: ${DYNAMODB_NOTIFICATIONS_TABLE_NAME:notification}

api:
  notify:
    api-key: ${API_NOTIFY_API_KEY}
    template:
        received-email: tbc-received-email-template-id
        approved-email: tbc-approved-email-template-id
        rejected-email: tbc-rejected-email-template-id
